### ISSUE TITLE
RenameOnUpdate Docker Path

### ISSUE THREAD

**Issue by Haezer89** [stashapp/CommunityScripts#146]
Hey Guys,
I am a little bit stuck at this plugin and don`t get it to work. Did anyone using it in a Docker Container and have it successfully running?
Already have problems with the logfile because of the path or something. Tried already a lot of variations. How to achieve this for example?

Thank you in Advance

**Comment by mitchwd** [comment]
Yeah, I got it working, but it was a bit of a nightmare to setup. 
In my docker-compose.yml, I had the `cache` folder mapped:
```yaml
services:
  stash:
   # other config here
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
    volumes:
      - ./cache:/cache
  ``` 

Then in the plugin config (`config/plugins/renamerOnUpdate/renamerOnUpdate_config.py`) I set the log file variable to this:
```python
log_file = r"/cache/renamerOnUpdate.txt"
```

Also, I created an empty txt file at `cache/renamerOnUpdate.txt`, because I had a feeling the renamer throws an error if the file doesn't exist in the first place. Ultimately, checking the error logs in Docker desktop was the most helpful thing.

I've attached my full config incase that helps (rename it to .py, as GitHub doesn't support raw .py)
[renamerOnUpdate_config.txt](https://github.com/stashapp/CommunityScripts/files/11358019/renamerOnUpdate_config.txt)
