### ISSUE TITLE
Stash Watcher - docker-compose.yml 

### ISSUE THREAD

**Issue by ben-ba** [stashapp/CommunityScripts#196]
after stash-wacher whitespaces are missing

```
version: "3.4"
services:
  stash-watcher:
  container_name: stash-watcher
  build: <path_to_stash-watcher_directory>
  volumes:
    #This is only required if you have to modify config.toml (if the defaults are fine you don't have to map this file)
    - ./config.toml:/config.toml:ro
    #This is the path to your stash content.  If you have multiple paths, map them here
    - /stash:/data:ro
  restart: unless-stopped
```

```
version: "3.4"
services:
  stash-watcher:
    container_name: stash-watcher
    build: <path_to_stash-watcher_directory>
    volumes:
      #This is only required if you have to modify config.toml (if the defaults are fine you don't have to map this file)
      - ./config.toml:/config.toml:ro
      #This is the path to your stash content.  If you have multiple paths, map them here
      - /stash:/data:ro
    restart: unless-stopped
```
